StarSubs/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StarSubs.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ViewBag.type = TempData["type"];
            ViewBag.size = TempData["size"];
            ViewBag.deal = TempData["deal"];


            ViewBag.ammount = TempData["ammount"];


            double dm;
            Double.TryParse(TempData["mealDeal"].ToString(), out dm);
            ViewBag.mealDeal = dm;

            double pc;
            Double.TryParse(TempData["Price"].ToString(), out pc);
            ViewBag.Price = pc;


            double tpc;
            Double.TryParse(TempData["totalPrice"].ToString(), out tpc);
            ViewBag.totalPrice = tpc;

            double tx;
            Double.TryParse(TempData["tax"].ToString(), out tx);
            ViewBag.tax = tx;

            double td;
            Double.TryParse(TempData["totalDue"].ToString(), out td);
            ViewBag.totalDue = td;

            return View();
        }

    
    public ActionResult Totals()
    {
        return View();
    }
}

StarSubs/Controllers/SubController.cs
using BLL;
using DLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StarSubs.Controllers
{
    public class SubController : Controller
    {
        int tax = 15;
        Dictionary<string, double> type = new Dictionary<string, double>()
        {
            { "TheMichaelJackson", 1},{"ThePrince",2 },{"TheBackStreetBoys",3 },{"TheBeyonce",4 },{"TheMadonna",5 }
              
        };
        Dictionary<string, double> size = new Dictionary<string, double>()
        {
            { "OneHitWonder", 1 },{"BList",2 },{"AList",3 },{"Superstar",4}

        };
        Dictionary<string, double> deal = new Dictionary<string, double>()
        {
            { "None", 0 },{"DrinkAndChips",1.25 },{"DrinkAndCookies",2 }

        };
        // GET: Sub
        public ActionResult Index()
        {
            var order = new OrderManipulation
            {

                Types = Enum.GetValues(typeof(SubType)).Cast<SubType>().Select(x => new SelectListItem { Text = x.ToString(), Value = x.ToString() }).AsEnumerable(),
                Sizes = Enum.GetValues(typeof(SubSize)).Cast<SubSize>().Select(x => new SelectListItem { Text = x.ToString(), Value = x.ToString() }).AsEnumerable(),
                Deals = Enum.GetValues(typeof(MealDeal)).Cast<MealDeal>().Select(x => x.ToString()).ToList()
            };
            return View(order);
        }
        [HttpPost]
        public ActionResult Index(OrderManipulation orderMan)
        {
            var order = new OrderManipulation
            {

                Types = Enum.GetValues(typeof(SubType)).Cast<SubType>().Select(x => new SelectListItem { Text = x.ToString(), Value = x.ToString() }).AsEnumerable(),
                Sizes = Enum.GetValues(typeof(SubSize)).Cast<SubSize>().Select(x => new SelectListItem { Text = x.ToString(), Value = x.ToString() }).AsEnumerable(),
                Deals = Enum.GetValues(typeof(MealDeal)).Cast<MealDeal>().Select(x => x.ToString()).ToList()
            };
           
            TempData["type"] = orderMan.Type;
            TempData["size"] = orderMan.Size;
            TempData["deal"] = orderMan.Deal;
            TempData["ammount"] = orderMan.Ammount;
            TempData["mealDeal"] = deal[orderMan.Deal];
            TempData["Price"] = (type[orderMan.Type] * size[orderMan.Size]) * orderMan.Ammount;
 
            TempData["totalPrice"] = ((type[orderMan.Type.ToString()] 
                * size[orderMan.Size.ToString()]) + deal[orderMan.Deal]) 
                * orderMan.Ammount;
           

            double price;
            Double.TryParse(TempData["totalPrice"].ToString(),out price);

            TempData["tax"] =  (price * tax / 100);

            double tx;
            Double.TryParse(TempData["tax"].ToString(), out tx);

   
            double tb;
            if (Double.TryParse(Session["totalBought"].ToString(), out tb))
            { }


            double at;
            if (Double.TryParse(Session["AllTax"].ToString(), out at))
            { }


            if (tb != 0 && Session["allOrders"] != null && at != 0)
            {
                Session["totalBought"] = tb + price;
                Session["allOrders"] += "Order type :" + TempData["type"] +  "Order size:" + TempData["size"] +
                    "Deal Type:" + TempData["deal"]  + "Order Ammount:" + TempData["ammount"];
                Session["AllTax"] = at + tx;
            }
            else
            {
                Session["totalBought"] = 0;
                Session["allOrders"] = "";
                Session["AllTax"] = 0;
            }
            return RedirectToAction("Index","Home");
        }

    }
}

StarSubs/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index2";
}

<h2>StarSub Receipt</h2>

@if (ViewBag.type != null)
{
    <p>Type of Sub: @ViewBag.type</p>
}
@if (ViewBag.size != null)
{
    <p>Size of Sub: @ViewBag.size</p>
}
@if (ViewBag.deal != null)
{
    <p>Size of Sub: @ViewBag.deal</p>
}
@if (ViewBag.ammount != null)
{
    <p>Size of Sub: @ViewBag.ammount</p>
}

@if (ViewBag.Price != null)
{
    <p>Total Price of Sub: @ViewBag.Price.ToString("C2")</p>
}
@if (ViewBag.mealDeal != null)
{
    <p>Price of Meal Deal: @ViewBag.mealDeal.ToString("C2")</p>
}

@if (ViewBag.tax != null)
{
    <p>Tax: @ViewBag.tax.ToString("C2")</p>
}
@if (ViewBag.totalDue != null)
{
    <p>Total Due: @ViewBag.totalDue.ToString("C2")</p>
}
@Html.ActionLink("Go Back", "Index", "Sub")
@Html.ActionLink("See Total", "Totals", "Home")

StarSubs/Views/Home/Totals.cshtml
@{
    ViewBag.Title = "Totals";
}

<h2>Totals</h2>

We made @Session["totalBought"]
<br>
These are the taxes @Session["AllTax"]
<br>
These are subs ordered @Session["allOrders"]

@Html.ActionLink("Go Back", "Index", "Sub")

StarSubs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

StarSubs/Views/Sub/Index.cshtml
@model OrderManipulation
@using BLL;

<head>
    <style>

        #type {
            float: left;
            width: 50%;
        }

        #size {
            float: right;
            width: 50%;
        }

        #size_inner {
            float: right;
        }

        #marg {
            margin-left: 50%;
        }

        #paragraph {
            float: none;
            width: 65%;
            margin: 5%;
        }
    </style>
</head>
<center>
    <h2>Welcome to StarSubs</h2>
</center>
<form method="post" >
    <div id="type">
        @Html.ListBoxFor(x => x.Type, Model.Types, new {required="required" })
    </div>
    <div id="size">
        @Html.ListBoxFor(x => x.Size, Model.Sizes, new { id = "size_inner" , required="required"})
    </div>
    <br>
    <div id="paragraph">

        <p id="marg"> Select a Meal Deal</p>

        <div id="marg">
            @Html.EditorFor(Model => Model.Ammount,
           new { htmlAttributes = new { @type = "number",
               @min = "0", @step = "1", @value = "1" , required="required" } })
            @foreach (var dealName in Model.Deals)
            {
                <label>
                    @Html.RadioButtonFor(x => x.Deal, dealName, new { @checked = "checked" })
                    @dealName
                </label>
            }
        </div>
        <br>
        <div id="marg">
            <button class="btn btn-primary" id="submit">Submit</button>

        </div>
    </div>
</form>

StarSubs/Views/Sub/Index3.cshtml
@{
    ViewBag.Title = "Index3";
}

<h2>StarSub Receipt</h2>

@if (ViewBag.type != null)
{
    <p>Type of Sub: @ViewBag.type</p>
}
@if (ViewBag.size != null)
{
    <p>Size of Sub: @ViewBag.size</p>
}
@if (ViewBag.deal != null)
{
    <p>Size of Sub: @ViewBag.deal</p>
}

@if (ViewBag.Price != null)
{
    <p>Total Price of Sub: @ViewBag.Price.ToString("C2")</p>
}
@if (ViewBag.mealDeal != null)
{
    <p>Price of Meal Deal: @ViewBag.mealDeal.ToString("C2")</p>
}

@if (ViewBag.Cost != null)
{
    <p>Cost: @ViewBag.Cost.ToString("C2")</p>
}
@if (ViewBag.tax != null)
{
    <p>Tax: @ViewBag.tax.ToString("C2")</p>
}
@if (ViewBag.totalDue != null)
{
    <p>Total Due: @ViewBag.totalDue.ToString("C2")</p>
}
@Html.ActionLink("Go Back", "Index", "Sub")